apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    type: pod
  namespace: test
spec:
  containers:
  - image: alpine
    name: alpine
    command: ["/bin/sh", "-c", "while true; do echo hello world; sleep 3600; done"]
 
