apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    type: rs
  name: nginx-replicaset
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
