apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine
  namespace: test
spec:
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - name: alpine
        image: alpine
        env:
        - name: DEMO_ENV
          value: "Coucou"
        command:
        - sleep
        - "3600"
