apiVersion: v1
kind: Service
metadata:
  namespace: test
  labels:
    type: deployment
  name: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  type: NodePort
  selector:
    app: nginx
